### ISSUE TITLE
Error code: 'ERR_OSSL_EVP_UNSUPPORTED' in latest docker build

### ISSUE THREAD

**Issue by davidhalldor** [hicetnunc2000/hicetnunc#1364]
**Describe the bug**
Can't run Docker image hicetnunc-ui@0.1.0 after build

**Screenshots**
- screenshots of your minting process
- screenshots of profiles affected
- screenshots of the browser console (in chrome windows, press ctrl + shift + j to open the developer console)
- screenshot from docker app
![image](https://user-images.githubusercontent.com/20148/144709656-1004a853-b9fd-470a-a845-acbd01aa68b5.png)

**To Reproduce**
1. cli cmd 1
```bash
docker image build -t hicetnunc:1.0
```
2. cli cmd 2

```bash
docker run -it -p 3000:3000 hicetnunc:1.0
```
3. cli stdout error
```bash
Starting the development server...

/usr/src/app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /usr/src/app/node_modules/webpack/lib/NormalModule.js:452:10
    at /usr/src/app/node_modules/webpack/lib/NormalModule.js:323:13
    at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /usr/src/app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: 
```bash
    ProductName:	macOS
    ProductVersion:	12.0.1
    BuildVersion:	21A559
```

**Comment by skenaja** [comment]
My guess is that `node:latest` has something in it that doesn't work with the code. The README says to use node 12, so maybe set the Dockerfile to use an older version of node?
