### ISSUE TITLE
https://www.hicetnunc.xyz/objkt/127774

### ISSUE THREAD

**Issue by abysms** [hicetnunc2000/hicetnunc#873]
https://www.hicetnunc.xyz/objkt/127774

ERROR MESSAGE:

(http 500) <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>TypeError: Cannot read property &#39;creators&#39; of undefined<br> &nbsp; &nbsp;at readObjkt (/var/task/lib/router/readObjkt.js:14:54)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre> </body> </html> 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please include the wallet address (tz...) and/or the OBJKT number.

**Comment by abysms** [comment]
SOLVED
